[package]
name = "mcp-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
rmcp = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
