apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp-log-parser
  namespace: edgeagent
  labels:
    app: mcp-log-parser
    component: mcp-server-wasm
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "5m"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      runtimeClassName: wasmtime
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
        - name: mcp-server
          image: srv2.ddps.cloud/wasm-mcp/log-parser:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: edgeagent-data
              mountPath: /edgeagent
      volumes:
        - name: edgeagent-data
          persistentVolumeClaim:
            claimName: edgeagent-data-pvc
