apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp-fetch
  namespace: edgeagent
  labels:
    app: mcp-fetch
    component: mcp-server-wasm
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "5m"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      nodeSelector:
        kubernetes.io/hostname: edge-nuc
      runtimeClassName: wasmtime
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
        - name: mcp-server
          image: srv2.ddps.cloud/wasm-mcp/fetch:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
